### ISSUE TITLE
Playground is down

### ISSUE THREAD

**Issue by teledyn** [json-ld/json-ld.org#728] opened 2020-05-20 16:02 UTC
See: https://tinyurl.com/kk7k5qt (A link to the JSON-LD playground)

jsonld.InvalidUrl: Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.

And that is just the tip of the iceberg of a lot of json-ld services being impacted. See also https://github.com/RDFLib/rdflib-jsonld/issues/84

**Comment by dlongley** [comment] 2020-05-20 16:03
The playground is up. It's a problem with schema.org. Their context isn't being served properly (it is ignoring a request for JSON-LD and only serving HTML):

Run:

`curl -v -H "accept: application/ld+json" "http://schema.org"`

You'll see the output is HTML.

**Comment by dlongley** [comment] 2020-05-20 16:04
Closing since the issue is elsewhere. Feel free to reopen/open another issue if there's an issue with the playground.

**Closed by dlongley** 2020-05-20 16:04 UTC

**Comment by davidlehn** [comment] 2020-05-22 22:04
It was a combination schema.org and jsonld.js problem.  Should be fixed now.

**Comment by gkellogg** [comment] 2020-05-22 22:16
Thanks, @davidlehn. As I recall, there's no test infrastructure for the xhr document loader.

**Comment by davidlehn** [comment] 2020-05-22 22:22
@gkellogg The playground users are the test infrastructure.  They found a bug, we fixed it. ;-)  But yes, that should be addressed at some point.
